---
port: 4080
host: 0.0.0.0
safe: false

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Testify Project Blog
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Testify Project Blog" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Software Testing Matters<h1>

  header_text_feature_image: #img/grand-canyon.jpg
  footer_text: >
   Copyright 2016-2017 Testify Project <a href="https://github.com/testify-project/blog.github.io/blob/master/LICENSE.md"><img src="https://img.shields.io/badge/Creative%20Commons-BY--SA-lightgrey.svg"</img></a>

  # Icons
  rss: false
  email_address: sharmarke.aden@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "testify-project"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, vendor]
permalink: /:title ## disables post output
timezone: PST
lsi: false
markdown: kramdown

kramdown:
  auto_ids:         true
  input:            GFM
  hard_wrap:        false

sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
